name: Periodic HealthCheck

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  fire_healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        with:
            url: https://fullstackopen11-pokedex.onrender.com/health
  