name: Deployment pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: install dependencies
        run: npm install 
      - name: linter
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
            command: npm run test:e2e
            start: npm run start-prod
            wait-on: http://localhost:5000
      - name: Trigger Deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        
      - name: Build successful
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ success() }}
        with: 
          severity: info
          details: build successful 
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          
      - name: Build failed
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ failure() }}
        with: 
          severity: error
          details: build failed - commit ${{ toJson(github.event.commits.id) }} has broken the build.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  

  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    runs-on: ubuntu-20.04
    needs: [simple_deployment_pipeline]
    steps:
      - uses: actions/checkout@v4
      - uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
